fn main() {
  write("err2");
  exit(2);
}
